### ISSUE TITLE
How it works ?

### ISSUE THREAD

**Issue by serkanbalta** [suncho26/opencart-js-css-minifier#6]
Hey, really appricieated.
I'm using oc 2.0.1.1 and i installed minifier succesfully.
How can i test the differency ?

**Comment by georgikolev7** [comment]
Hey, you can use [Google PageSpeed Insights](https://developers.google.com/speed/pagespeed/insights/) or [Varvy PageSpeed](https://varvy.com/pagespeed/)

**Comment by serkanbalta** [comment]
thank you so much
